exports.USER_TYPE = {
    ADMIN: 'ADMIN',
    STUDENT: 'STUDENT',
    LECTURER: 'LECTURER'
}

exports.ATTDENDANCE_STATUS = {
    UNMARKED: 'UNMARKED',
    PRESENT: 'PRESENT',
    ABSENT: 'ABSENT',
    LATE: 'LATE'
}
